version: '3'

services:
    app:
        build: ./docker/dockerfiles/app
        working_dir: /resource/
        environment:
            docker: "true"
        ports:
            - 80:80
        volumes:
            - .:/resource

    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mozk
        ports:
            - 3306:3306
        volumes:
            - ./volumes/mysql:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - 8080:80
        volumes:
            - ./volumes/phpmyadmin/sessions:/sessions
        links:
            - db
