version: '3'

services:
    app:
        image: php:7.3-fpm
        working_dir: /resource/
        environment:
            docker: "true"
        volumes:
            - .:/resource

    nginx:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./docker/resources/nginx/conf.d:/etc/nginx/conf.d
        links:
            - app

    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: mozk
            MYSQL_PASSWORD: mozk
            MYSQL_DATABASE: mozk
        ports:
            - 3306:3306
        volumes:
            - ./docker/volumes/mysql:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - 8080:80
        volumes:
            - ./docker/volumes/phpmyadmin/sessions:/sessions
        links:
            - db
